version: '3.8'

services:
  test-installer:
    image: curlimages/curl:latest
    container_name: test_install_script
    user: root # Needed if install.sh writes to /usr/local/bin or system dirs
    volumes:
      # Mount your local install script into the container
      # - ./install.sh:/tmp/install.sh:ro
      - ../../install.sh:/tmp/install.sh:ro
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /bin/sh /tmp/install.sh
      # - |
      #   chmod +x /tmp/install.sh
      #   /tmp/install.sh
