// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
// import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Our notion of production & development environment is different from
    // standard web apps: production means xdg compliant installation,
    // development is just current repo directory.
    // url: process.env["DATABASE_URL"],
    url: "file:./prisma/app.db",
  },
});
