name: hh200d
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - lsp
  - text
  - hh200
  - aeson
  - network
  - co-log-core
  - gitrev

library:
  source-dirs: src
  build-tools:
    - bnfc:bnfc
executables:
  hh200d:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
