snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/26.yaml
packages:
- .
extra-deps:
  - ../hh200
  - ../../bel-expr
  - ../../http-client/http-client-tls
