name:                hh200-lsp
version:             0.1.0.0
github:              "tbmreza/hh200"
license:             MIT
author:              "Reza Handzalah"
maintainer:          "rezahandzalah@gmail.com"
copyright:           "2024 Reza"

dependencies:
- base >= 4.7 && < 5
- lsp
- text
- lens
- mtl

executables:
  hh200-lsp:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - lsp
    - text
    - lens
    - mtl
