-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Hh200.

module Hh200.AbsHh where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Str = Str String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Int = Int Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Script = Script [TopLevel]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TopLevel = TopLevelConfig ConfigBlock | TopLevelCall CallItem
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConfigBlock = ConfigBlock [ConfigItem]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ConfigItem = ConfigItem Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CallItem
    = CallItem DepsClause Request Response
    | CallItemNoResponse DepsClause Request
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DepsClause = DepsClause [Str] String | NoDepsClause String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Request
    = Request Method Url [Binding] String
    | RequestNoPayload Method Url [Binding]
    | RequestNoBindings Method Url String
    | RequestMin Method Url
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Binding = Binding Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Response
    = Response [Int] ResponseBody | ResponseNoCodes ResponseBody
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ResponseBody
    = ResponseBody Captures Asserts
    | ResponseBodyCapturesOnly Captures
    | ResponseBodyAssertsOnly Asserts
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Captures = Captures [Binding]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Asserts = Asserts [Str]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Method
    = MethodGET
    | MethodPOST
    | MethodPUT
    | MethodDELETE
    | MethodPATCH
    | MethodOPTIONS
    | MethodHEAD
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Url = Url Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)
