-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for PrintHh.

module Hh200.PrintHh where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsHh

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsHh.Ident where
  prt _ (AbsHh.Ident i) = doc $ showString i
instance Print [AbsHh.ConfigItem] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsHh.Binding] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsHh.Str] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsHh.Int] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsHh.Str where
  prt i = \case
    AbsHh.Str str -> prPrec i 0 (concatD [printString str])

instance Print AbsHh.Int where
  prt i = \case
    AbsHh.Int n -> prPrec i 0 (concatD [prt 0 n])

instance Print AbsHh.Script where
  prt i = \case
    AbsHh.Script toplevels -> prPrec i 0 (concatD [prt 0 toplevels])

instance Print [AbsHh.TopLevel] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsHh.TopLevel where
  prt i = \case
    AbsHh.TopLevelConfig configblock -> prPrec i 0 (concatD [prt 0 configblock])
    AbsHh.TopLevelCall callitem -> prPrec i 0 (concatD [prt 0 callitem])

instance Print AbsHh.ConfigBlock where
  prt i = \case
    AbsHh.ConfigBlock configitems -> prPrec i 0 (concatD [doc (showString "["), doc (showString "Configs"), doc (showString "]"), prt 0 configitems])

instance Print AbsHh.ConfigItem where
  prt i = \case
    AbsHh.ConfigItem id_ str -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), printString str])

instance Print AbsHh.CallItem where
  prt i = \case
    AbsHh.CallItem depsclause request response -> prPrec i 0 (concatD [prt 0 depsclause, prt 0 request, prt 0 response])
    AbsHh.CallItemNoResponse depsclause request -> prPrec i 0 (concatD [prt 0 depsclause, prt 0 request])

instance Print AbsHh.DepsClause where
  prt i = \case
    AbsHh.DepsClause strs str -> prPrec i 0 (concatD [prt 0 strs, doc (showString "then"), printString str])
    AbsHh.NoDepsClause str -> prPrec i 0 (concatD [printString str])

instance Print AbsHh.Request where
  prt i = \case
    AbsHh.Request method url bindings str -> prPrec i 0 (concatD [prt 0 method, prt 0 url, prt 0 bindings, doc (showString "{"), printString str, doc (showString "}")])
    AbsHh.RequestNoPayload method url bindings -> prPrec i 0 (concatD [prt 0 method, prt 0 url, prt 0 bindings])
    AbsHh.RequestNoBindings method url str -> prPrec i 0 (concatD [prt 0 method, prt 0 url, doc (showString "{"), printString str, doc (showString "}")])
    AbsHh.RequestMin method url -> prPrec i 0 (concatD [prt 0 method, prt 0 url])

instance Print AbsHh.Binding where
  prt i = \case
    AbsHh.Binding id_ str -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), printString str])

instance Print AbsHh.Response where
  prt i = \case
    AbsHh.Response ints responsebody -> prPrec i 0 (concatD [doc (showString "HTTP"), prt 0 ints, prt 0 responsebody])
    AbsHh.ResponseNoCodes responsebody -> prPrec i 0 (concatD [prt 0 responsebody])

instance Print AbsHh.ResponseBody where
  prt i = \case
    AbsHh.ResponseBody captures asserts -> prPrec i 0 (concatD [prt 0 captures, prt 0 asserts])
    AbsHh.ResponseBodyCapturesOnly captures -> prPrec i 0 (concatD [prt 0 captures])
    AbsHh.ResponseBodyAssertsOnly asserts -> prPrec i 0 (concatD [prt 0 asserts])

instance Print AbsHh.Captures where
  prt i = \case
    AbsHh.Captures bindings -> prPrec i 0 (concatD [doc (showString "["), doc (showString "Captures"), doc (showString "]"), prt 0 bindings])

instance Print AbsHh.Asserts where
  prt i = \case
    AbsHh.Asserts strs -> prPrec i 0 (concatD [doc (showString "["), doc (showString "Asserts"), doc (showString "]"), prt 0 strs])

instance Print AbsHh.Method where
  prt i = \case
    AbsHh.MethodGET -> prPrec i 0 (concatD [doc (showString "GET")])
    AbsHh.MethodPOST -> prPrec i 0 (concatD [doc (showString "POST")])
    AbsHh.MethodPUT -> prPrec i 0 (concatD [doc (showString "PUT")])
    AbsHh.MethodDELETE -> prPrec i 0 (concatD [doc (showString "DELETE")])
    AbsHh.MethodPATCH -> prPrec i 0 (concatD [doc (showString "PATCH")])
    AbsHh.MethodOPTIONS -> prPrec i 0 (concatD [doc (showString "OPTIONS")])
    AbsHh.MethodHEAD -> prPrec i 0 (concatD [doc (showString "HEAD")])

instance Print AbsHh.Url where
  prt i = \case
    AbsHh.Url id_ -> prPrec i 0 (concatD [prt 0 id_])
