-- File generated by the BNF Converter (bnfc 2.9.6.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module Hh200.SkelHh where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsHh

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsHh.Ident -> Result
transIdent x = case x of
  AbsHh.Ident string -> failure x

transStr :: AbsHh.Str -> Result
transStr x = case x of
  AbsHh.Str string -> failure x

transInt :: AbsHh.Int -> Result
transInt x = case x of
  AbsHh.Int integer -> failure x

transScript :: AbsHh.Script -> Result
transScript x = case x of
  AbsHh.Script toplevels -> failure x

transTopLevel :: AbsHh.TopLevel -> Result
transTopLevel x = case x of
  AbsHh.TopLevelConfig configblock -> failure x
  AbsHh.TopLevelCall callitem -> failure x

transConfigBlock :: AbsHh.ConfigBlock -> Result
transConfigBlock x = case x of
  AbsHh.ConfigBlock configitems -> failure x

transConfigItem :: AbsHh.ConfigItem -> Result
transConfigItem x = case x of
  AbsHh.ConfigItem ident string -> failure x

transCallItem :: AbsHh.CallItem -> Result
transCallItem x = case x of
  AbsHh.CallItem depsclause request response -> failure x
  AbsHh.CallItemNoResponse depsclause request -> failure x

transDepsClause :: AbsHh.DepsClause -> Result
transDepsClause x = case x of
  AbsHh.DepsClause strs string -> failure x
  AbsHh.NoDepsClause string -> failure x

transRequest :: AbsHh.Request -> Result
transRequest x = case x of
  AbsHh.Request method url bindings string -> failure x
  AbsHh.RequestNoPayload method url bindings -> failure x
  AbsHh.RequestNoBindings method url string -> failure x
  AbsHh.RequestMin method url -> failure x

transBinding :: AbsHh.Binding -> Result
transBinding x = case x of
  AbsHh.Binding ident string -> failure x

transResponse :: AbsHh.Response -> Result
transResponse x = case x of
  AbsHh.Response ints responsebody -> failure x
  AbsHh.ResponseNoCodes responsebody -> failure x

transResponseBody :: AbsHh.ResponseBody -> Result
transResponseBody x = case x of
  AbsHh.ResponseBody captures asserts -> failure x
  AbsHh.ResponseBodyCapturesOnly captures -> failure x
  AbsHh.ResponseBodyAssertsOnly asserts -> failure x

transCaptures :: AbsHh.Captures -> Result
transCaptures x = case x of
  AbsHh.Captures bindings -> failure x

transAsserts :: AbsHh.Asserts -> Result
transAsserts x = case x of
  AbsHh.Asserts strs -> failure x

transMethod :: AbsHh.Method -> Result
transMethod x = case x of
  AbsHh.MethodGET -> failure x
  AbsHh.MethodPOST -> failure x
  AbsHh.MethodPUT -> failure x
  AbsHh.MethodDELETE -> failure x
  AbsHh.MethodPATCH -> failure x
  AbsHh.MethodOPTIONS -> failure x
  AbsHh.MethodHEAD -> failure x

transUrl :: AbsHh.Url -> Result
transUrl x = case x of
  AbsHh.Url ident -> failure x
