name:                hh200
version:             0.0.1
github:              "tbmreza/hh200"
license:             MIT
author:              "Reza Handzalah"
maintainer:          "rezahandzalah@gmail.com"
copyright:           "2024 Reza"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Statically-checked DSL for testing HTTP servers
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tbmreza/hh200#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Hh200.Cli
  - Hh200.ContentType
  - Hh200.Execution
  - Hh200.Fearless
  - Hh200.Graph
  - Hh200.Http
  - Hh200.Scanner
  - Hh200.Types
  default-extensions:
  - OverloadedStrings
  dependencies:
  - text
  - transformers
  - process
  - http-client
  - http-client-tls
  - bytestring
  - mtl
  - filepath
  - random
  - async
  - directory
  - fast-logger
  - strict
  - keys
  - unordered-containers
  - case-insensitive
  - sqlite-simple
  - time
  # from library
  - array
  - hashtables
  - split
  - ghc
  - http-types
  - http-conduit
  - toml-parser
  - yaml
  - vector
  - parsec
  - aeson
  - aeson-jsonpath >= 0.3.0.2 && < 0.4.0.0
  - bel-expr
  - optparse-applicative

executables:
  hh200:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - hh200

tests:
  hh200-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hh200
    - http-client      # imported as Prim
    - http-client-tls  # imported as Prim
    - transformers
    - tasty
    - tasty-hunit
    - unordered-containers
    - text
